### ISSUE TITLE
Filter models for the coverage

### ISSUE THREAD

**Issue by sumit-sampang-rai** [slidoapp/dbt-coverage#24]
Please add options in the CLI to include and exclude models to filter out the checks in some of the models or a path.

**Comment by sweco** [comment]
Hey @mailtosumitrai, thanks for you suggestion! This is definitely a good idea 😊 I'm sorry but I don't know when I'll have time to implement this. However, if anyone is open to contributing, we can brainstorm together how it could work.

**Comment by JadAbdallah** [comment]
Hey @sweco ! Any chance there's been updates on this? I think it would be useful to be able to select specific models or folders to run the coverage test on.

**Comment by followingell** [comment]
Please find my PR that I believe closes this Issue here:
- https://github.com/slidoapp/dbt-coverage/pull/45

_cc: @sweco_
