### ISSUE TITLE
dbt 1.1 / manifest v5 support ?

### ISSUE THREAD

**Issue by aa-matthias** [slidoapp/dbt-coverage#31]
Hi,

are you going to add support for manifest v5 as well? It's currently outputting a warning aying manifest v5 is not supported.

Thanks a lot!

**Comment by mrshu** [comment]
Hi @aa-matthias, this is indeed something we'll look at supporting in the future 🙂

**Comment by reegs** [comment]
@mrshu Based on the dbt version [changelogs](https://github.com/dbt-labs/dbt-core/blob/1.1.latest/CHANGELOG.md) and the issues included in 1.1 related to the manifest [1](https://github.com/dbt-labs/dbt-core/pull/5346/files) and [2](https://github.com/dbt-labs/dbt-core/issues/5213), but in particular the first one I linked, it seems like dbt-core is treating version 5 of the manifest as compatible with version 4 so it shouldn't require any changes in parsing logic, just adding that versions 4 and 5 of the manifest can be treated the same by `dbt-coverage`

**Comment by mrshu** [comment]
Cool, thanks @reegs!

@sweco what do you say? Would it make sense to support the version 5 of the manifest as well?

**Comment by sweco** [comment]
Hey all, thank you all for analyzing the changes in the manifest. 😊 I'm marking manifest v5 to the list of the supported versions in https://github.com/slidoapp/dbt-coverage/pull/34.

**Comment by sweco** [comment]
Released in https://github.com/slidoapp/dbt-coverage/releases/tag/v0.2.1. Thank you for reporting the issue and thus helping with the development of the project! 😊
