### ISSUE TITLE
Add support for Manifest v6

### ISSUE THREAD

**Issue by reegs** [slidoapp/dbt-coverage#35]
dbt has released [version 1.2](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.2) and bumped the manifest version to v6 as part of this [release](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.2?#for-consumers-of-dbt-artifacts-metadata).

They have allowed [manifest v6 to defer to v4 and v5 of the manifest](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/manifest.py#L1205) which means that changes are not breaking. They are related to adding information about [configs](https://docs.getdbt.com/reference/global-configs) and [metrics](https://docs.getdbt.com/docs/building-a-dbt-project/metrics). Neither of these are currently consumed from the manifest by [dbt coverage](https://github.com/slidoapp/dbt-coverage/blob/main/dbt_coverage/__init__.py#L86)

I believe this means `dbt-coverage` can add manifest `v6` support without fundamental changes to the project

**Comment by sweco** [comment]
Hey @reegs, thanks for reporting the issue and checking the status. I'll add manifest `v6` to the list of supported versions.

**Comment by reegs** [comment]
Thank you @sweco !
