### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by RoyalTS** [slidoapp/dbt-coverage#63]
Interrogate [supports use as a pre-commit hook](https://interrogate.readthedocs.io/en/latest/#other-usage). Would it be possible to support the same functionality and to e.g. fail a git commit if coverage drops below some threshold?

**Comment by mrshu** [comment]
Hi @RoyalTS,

Although we haven't tried it ourselves, in principle there shouldn't be anything preventing `dbt-coverage` from being run in a pre-commit hook. Would you be up for trying to set it up and letting us know if it worked for you?

**Comment by RoyalTS** [comment]
I have this working but have decided not to use it. Having to run `dbt docs generate` every time means each commit then takes an enormously long time to run.

**Comment by mrshu** [comment]
Thanks for sharing your experience @RoyalTS. Unfortunately, there is little we can do in order to avoid `dbt docs generate` -- that is why in our internal usage we use `dbt-coverage` primarily in CI/CD pipelines rather than in a pre-commit hook.
