### ISSUE TITLE
Can't specify environment variables or target path when running dbt-coverage compute doc

### ISSUE THREAD

**Issue by remolloy1010** [slidoapp/dbt-coverage#65]
I have my target path in the dbt_project.yml file as an environment variable. I get this failure when I try to run the command `dbt-coverage compute doc --cov-report coverage-doc.json` because the manifest.json was written to a folder based on what I set my environment variable as. 

```
FileNotFoundError: manifest.json not found in target or in custom path - before using dbt-coverage, run a dbt command that creates manifest artifact (see: https://docs.getdbt.com/reference/artifacts/manifest-json)
```

Is there a way to either pass an environment variable or configure (at runtime) where to look for the manifest.json file?

**Comment by sweco** [comment]
Hey @remolloy1010, please check the command's manual page. You can use `--project-dir` or `--run-artifacts-dir` for configuration.

```
> dbt-coverage compute --help

...
Options:
  --project-dir PATH              dbt project directory path.  [default: .]
  --run-artifacts-dir PATH        Custom directory path for catalog and
                                  manifest files
...
```
